include:
  - .gitlab-ci/job-definitions.yml
  - .gitlab-ci/global-declarations.yml
  - .gitlab-ci/devices.yml

rootfs-amd64-phosh:
  extends:
    - .rootfs-generic
    - .arch-amd64
    - .shell-phosh

rootfs-amd64-plasma-mobile:
  extends:
    - .rootfs-generic
    - .arch-amd64
    - .shell-plasma-mobile

rootfs-arm64-phosh:
  extends:
    - .rootfs-generic
    - .arch-arm64
    - .shell-phosh

rootfs-arm64-plasma-mobile:
  extends:
    - .rootfs-generic
    - .arch-arm64
    - .shell-plasma-mobile

installfs-arm64:
  extends:
    - .rootfs-installer
    - .arch-arm64

devicefs-librem5-phosh:
  extends:
    - .devicefs
    - .device-librem5
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

devicefs-librem5-plasma-mobile:
  extends:
    - .devicefs
    - .device-librem5
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

devicefs-pinephone-phosh:
  extends:
    - .devicefs
    - .device-pinephone
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

devicefs-pinephone-plasma-mobile:
  extends:
    - .devicefs
    - .device-pinephone
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

devicefs-pinephonepro-phosh:
  extends:
    - .devicefs
    - .device-pinephonepro
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

devicefs-pinephonepro-plasma-mobile:
  extends:
    - .devicefs
    - .device-pinephonepro
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

#devicefs-pinetab-phosh:
#  extends:
#    - .devicefs
#    - .device-pinetab
#    - .shell-phosh
#  needs:
#    - rootfs-arm64-phosh

devicefs-pinetab2-phosh:
 extends:
   - .devicefs
   - .device-pinetab2
   - .shell-phosh
 needs:
   - rootfs-arm64-phosh

devicefs-pinetab2-plasma-mobile:
 extends:
   - .devicefs
   - .device-pinetab2
   - .shell-plasma-mobile
 needs:
   - rootfs-arm64-plasma-mobile

image-pinephone-phosh:
  extends:
    - .image
    - .device-pinephone
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-pinephone-plasma-mobile:
  extends:
    - .image
    - .device-pinephone
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-pinephonepro-phosh:
  extends:
    - .image
    - .device-pinephonepro
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-pinephonepro-plasma-mobile:
  extends:
    - .image
    - .device-pinephonepro
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

#image-pinetab-phosh:
#  extends:
#    - .image
#    - .device-pinetab
#    - .shell-phosh
#  needs:
#    - rootfs-arm64-phosh

image-pinetab2-phosh:
  extends:
    - .image
    - .device-pinetab2
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-pinetab2-plasma-mobile:
  extends:
    - .image
    - .device-pinetab2
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-librem5-phosh:
  extends:
    - .image
    - .device-librem5
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-librem5-plasma-mobile:
  extends:
    - .image
    - .device-librem5
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-sdm845-phosh:
  extends:
    - .image
    - .device-sdm845
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-sdm845-plasma-mobile:
  extends:
    - .image
    - .device-sdm845
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-sm7225-phosh:
  extends:
    - .image
    - .device-sm7225
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-sm7225-plasma-mobile:
  extends:
    - .image
    - .device-sm7225
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-amd64-phosh:
  extends:
    - .image
    - .device-amd64
    - .shell-phosh
  needs:
    - rootfs-amd64-phosh

image-amd64-plasma-mobile:
  extends:
    - .image
    - .device-amd64
    - .shell-plasma-mobile
  needs:
    - rootfs-amd64-plasma-mobile

image-amd64-nonfree-phosh:
  extends:
    - .image
    - .device-amd64-nonfree
    - .shell-phosh
  needs:
    - rootfs-amd64-phosh

image-amd64-nonfree-plasma-mobile:
  extends:
    - .image
    - .device-amd64-nonfree
    - .shell-plasma-mobile
  needs:
    - rootfs-amd64-plasma-mobile

installer-librem5-phosh:
  extends:
    - .installer
    - .device-librem5
    - .shell-phosh
  needs:
    - installfs-arm64
    - devicefs-librem5-phosh

installer-librem5-plasma-mobile:
  extends:
    - .installer
    - .device-librem5
    - .shell-plasma-mobile
  needs:
    - installfs-arm64
    - devicefs-librem5-plasma-mobile

installer-pinephone-phosh:
  extends:
    - .installer
    - .device-pinephone
    - .shell-phosh
  needs:
    - installfs-arm64
    - devicefs-pinephone-phosh

installer-pinephone-plasma-mobile:
  extends:
    - .installer
    - .device-pinephone
    - .shell-plasma-mobile
  needs:
    - installfs-arm64
    - devicefs-pinephone-plasma-mobile

installer-pinephonepro-phosh:
  extends:
    - .installer
    - .device-pinephonepro
    - .shell-phosh
  needs:
    - installfs-arm64
    - devicefs-pinephonepro-phosh

installer-pinephonepro-plasma-mobile:
  extends:
    - .installer
    - .device-pinephonepro
    - .shell-plasma-mobile
  needs:
    - installfs-arm64
    - devicefs-pinephonepro-plasma-mobile

#installer-pinetab-phosh:
#  extends:
#    - .installer
#    - .device-pinetab
#    - .shell-phosh
#  needs:
#    - installfs-arm64
#    - devicefs-pinetab-phosh

installer-pinetab2-phosh:
 extends:
   - .installer
   - .device-pinetab2
   - .shell-phosh
 needs:
   - installfs-arm64
   - devicefs-pinetab2-phosh

installer-pinetab2-plasma-mobile:
 extends:
   - .installer
   - .device-pinetab2
   - .shell-plasma-mobile
 needs:
   - installfs-arm64
   - devicefs-pinetab2-plasma-mobile
