chipset = "sm8250"


[bootimg]

base = 0x0

kernel = 0x8000

ramdisk = 0x200000

second = 0x0

tags = 0x1e0000

pagesize = 4096

dtb_size = 1580275

dtb_offset = 0x1f00000


[[device]]

vendor = "samsung"

model = "s20fe"

variant = "r8q"

chipset = "sm8250"

append = "root=/dev/block/bootdevice/by-name/userdata rw splash quiet rootmnt=/root console=ttyMSM0,115200"



[[device]]
vendor = "oneplus"
model = "fajita"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "shift"
model = "axolotl"
append = "console=ttyMSM0,115200"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "ebbg"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "tianma"

[[device]]
vendor = "fairphone"
model = "fp4"
chipset = "sm7225"

[[device]]
vendor = "fairphone"
model = "fp5"
chipset = "qcm6490"
bootimg = { version = 2, base = 0x0, kernel = 0x8000, ramdisk = 0x01000000, dtb = 0x01f00000, second = 0x0, tags = 0x100, pagesize = 4096 }
